# see https://github.com/cypress-io/circleci-orb
version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      # Checkout repository
      - checkout

      # Restore cache
      - restore_cache:
          key: yarn-cache-{{ checksum "yarn.lock" }}

      # Install dependencies
      - run:
          name: Install Dependencies
          command: NODE_ENV=dev yarn

      # Keep cache
      - save_cache:
          key: yarn-cache-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"

      # Type Check
      - run:
          name: Type Check
          command: yarn type-check

      # Cypress Tests
      - run:
          name: Tests
          command: yarn test

      # Coverage Soon
